#!/bin/bash                                                                                                                                                     
cat << EOF >> "mvws.conf"
$(
echo ""
for i in {0..9}; do
    for j in {0..9}; do
        echo "mode \"mvws$i$j\" {"
            for k in {0..9}; do
                if [ $i -eq 0 ] && [ $j -eq 0 ]; then
                    echo "    bindsym $k mode default, move container to workspace $k"
                elif [ $i -eq 0 ]; then
                    echo "    bindsym $k mode default, move container to workspace $j$k"
                else
                    echo "    bindsym $k mode default, move container to workspace $i$j$k"
                fi
            done
            echo ""

            for k in {0..9}; do
                if [ $i -eq 0 ] && [ $j -eq 0 ]; then
                    echo "    bindsym \$mod+$k mode default, move container to workspace $k"
                elif [ $i -eq 0 ]; then
                    echo "    bindsym \$mod+$k mode default, move container to workspace $j$k"
                else
                    echo "    bindsym \$mod+$k mode default, move container to workspace $i$j$k"
                fi
            done
            echo ""

            for k in {0..9}; do
                if [ $i -eq 0 ] && [ $j -eq 0 ]; then
                    echo "    bindsym \$mod+Shift+$k mode default, move container to workspace $k"
                elif [ $i -eq 0 ]; then
                    echo "    bindsym \$mod+Shift+$k mode default, move container to workspace $j$k"
                else
                    echo "    bindsym \$mod+Shift+$k mode default, move container to workspace $i$j$k"
                fi
            done
            echo ""

        if [ $i -eq 0 ]; then
            echo "    bindsym Return mode default, move container to workspace $j"
            echo "    bindsym \$mod+Return mode default, move container to workspace $j"
            echo "    bindsym \$mod+Shift+Return mode default, move container to workspace $j"
            echo "    bindsym Backspace mode default"
            echo "    bindsym \$mod+Backspace mode default"
            echo "    bindsym \$mod+Shift+Backspace mode default"
        else
            echo "    bindsym Return mode default, move container to workspace $i$j"
            echo "    bindsym \$mod+Return mode default, move container to workspace $i$j"
            echo "    bindsym \$mod+Shift+Return mode default, move container to workspace $i$j"
            echo "    bindsym Backspace mode \"ws$i$j\""
            echo "    bindsym \$mod+Backspace mode \"ws$i$j\""
            echo "    bindsym \$mod+Shift+Backspace mode \"ws$i$j\""
        fi
        echo "    bindsym Escape mode default"
        echo "    bindsym \$mod+Escape mode default"
        echo "    bindsym \$mod+Shift+Escape mode default"
        echo "}"
        echo ""
    done
done
)
EOF

cat << EOF >> "mvws.conf"
$(
echo ""
for i in {0..9}; do
    echo "mode \"mvws$i\" {"
    for j in {0..9}; do
        echo "    bindsym $j mode mvws$i$j"
    done
    echo ""

    for j in {0..9}; do
        echo "    bindsym \$mod+$j mode mvws$i$j"
    done
    echo ""

    for j in {0..9}; do
        echo "    bindsym \$mod+Shift+$j mode mvws$i$j"
    done
    echo ""

    echo "    bindsym Return mode default, move container to workspace $i"
    echo "    bindsym \$mod+Return mode default, move container to workspace $i"
    echo "    bindsym Backspace mode default"
    echo "    bindsym \$mod+Backspace mode default"
    echo "    bindsym \$mod+Shift+Backspace mode default"
    echo "    bindsym Escape mode default"
    echo "    bindsym \$mod+Escape mode default"
    echo "    bindsym \$mod+Shift+Escape mode default"
    echo "}"
    echo ""
done
)
EOF

cat << EOF >> "mvws.conf"
$(
echo ""
for i in {0..9}; do
    echo "bindsym \$mod+Shift+$i mode mvws$i"
done
echo ""
)
EOF
