#!/bin/bash                                                                                                                                                     
cat << EOF >> "ws.conf"
$(
echo ""
for i in {0..9}; do
    for j in {0..9}; do
        echo "mode \"ws$i$j\" {"
            for k in {0..9}; do
                if [ $i -eq 0 ] && [ $j -eq 0 ]; then
                    echo "    bindsym $k mode default, workspace $k"
                elif [ $i -eq 0 ]; then
                    echo "    bindsym $k mode default, workspace $j$k"
                else
                    echo "    bindsym $k mode default, workspace $i$j$k"
                fi
            done
            echo ""

            for k in {0..9}; do
                if [ $i -eq 0 ] && [ $j -eq 0 ]; then
                    echo "    bindsym \$mod+$k mode default, workspace $k"
                elif [ $i -eq 0 ]; then
                    echo "    bindsym \$mod+$k mode default, workspace $j$k"
                else
                    echo "    bindsym \$mod+$k mode default, workspace $i$j$k"
                fi
            done
            echo ""

        if [ $i -eq 0 ]; then
            echo "    bindsym Return mode default, workspace $j"
            echo "    bindsym \$mod+Return mode default, workspace $j"
            echo "    bindsym Backspace mode default"
            echo "    bindsym \$mod+Backspace mode default"
        else
            echo "    bindsym Return mode default, workspace $i$j"
            echo "    bindsym \$mod+Return mode default, workspace $i$j"
            echo "    bindsym Backspace mode \"ws$i\""
            echo "    bindsym \$mod+Backspace mode \"ws$i\""
        fi
        echo "    bindsym Escape mode default"
        echo "    bindsym \$mod+Escape mode default"
        echo "}"
        echo ""
    done
done
)
EOF

cat << EOF >> "ws.conf"
$(
echo ""
for i in {0..9}; do
    echo "mode \"ws$i\" {"
    for j in {0..9}; do
        echo "    bindsym $j mode ws$i$j"
    done
    echo ""

    for j in {0..9}; do
        echo "    bindsym \$mod+$j mode ws$i$j"
    done
    echo ""

    echo "    bindsym Return mode default, workspace $i"
    echo "    bindsym \$mod+Return mode default, workspace $i"
    echo "    bindsym Backspace mode default"
    echo "    bindsym \$mod+Backspace mode default"
    echo "    bindsym Escape mode default"
    echo "    bindsym \$mod+Escape mode default"
    echo "}"
    echo ""
done
)
EOF

cat << EOF >> "ws.conf"
$(
echo ""
for i in {0..9}; do
    echo "bindsym \$mod+$i mode ws$i"
done
echo ""
)
EOF
